
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 17 20:52:30 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 12;
  public static final int CHAR = 46;
  public static final int CONST = 4;
  public static final int GE = 34;
  public static final int HASH = 39;
  public static final int LPAREN = 14;
  public static final int SEMI = 7;
  public static final int MINUS = 27;
  public static final int RPAREN = 15;
  public static final int LT = 35;
  public static final int BOOL = 47;
  public static final int COMMA = 6;
  public static final int INC = 24;
  public static final int DIV = 29;
  public static final int PLUS = 26;
  public static final int ASSIGN = 5;
  public static final int MAIN = 16;
  public static final int IF = 22;
  public static final int CARET = 40;
  public static final int CONDOP = 41;
  public static final int DOT = 8;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int RBRACKET = 13;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int NUMBER = 45;
  public static final int MOD = 30;
  public static final int IDENT = 44;
  public static final int VOID = 17;
  public static final int EQ = 31;
  public static final int COLON = 9;
  public static final int LBRACE = 10;
  public static final int ELSE = 23;
  public static final int ENUM = 3;
  public static final int READ = 18;
  public static final int FINAL = 42;
  public static final int RBRACE = 11;
  public static final int PROG = 2;
  public static final int NE = 32;
  public static final int QUESTION = 37;
  public static final int LEN = 20;
  public static final int AT = 43;
  public static final int DEC = 25;
  public static final int DUPQUEOP = 38;
  public static final int GT = 33;
  public static final int PRINT = 19;
}

